site_name: Quicklook Docs
site_url: https://github.com/samsammurphy/quicklook

nav:
    - Home: index.md
    - Installation: installation.md
    - Getting Started: getting_started.md
    - Command Line: cli.md

theme: readthedocs